export type CsvIssue={row:number;field?:string;message:string;severity:'error'|'warning'};
export type CsvResult={headers:string[];rows:Record<string,string>[];issues:CsvIssue[];duplicates:number[];mapping:Record<string,string|null>};
export const BROKER_PRESETS={
 mt5:['Ticket','Open Time','Type','Volume','Symbol','Open Price','Close Time','Close Price','Commission','Swap','Profit'],
 ctrader:['Position ID','Entry Time','Direction','Volume','Symbol','Entry Price','Closing Time','Exit Price','Commission','Swap','Net P/L'],
 ibkr:['Trade ID','Date/Time','Side','Quantity','Symbol','T. Price','Realized P/L','Commission','Fees'],
 oanda:['Trade ID','Open Time','Type','Units','Instrument','Price','Close Time','Close Price','Financing','Commission','P/L'],
 tradingview:['Trade ID','Date/Time','Side','Quantity','Symbol','Price','Close Time','Close Price','Commission','P/L']
} as const;
const aliases:Record<string,string[]>= {id:['ticket','trade id','position id','tradeid'],date:['open time','entry time','date/time','date'],symbol:['symbol','instrument','pair'],side:['type','direction','side'],volume:['volume','quantity','units'],entry:['open price','entry price','t. price','price'],exit:['close price','exit price'],pnl:['profit','net p/l','realized p/l','p/l']};
export function normalizeHeader(s:string){return s.trim().toLowerCase().replace(/[._-]+/g,' ').replace(/\s+/g,' ')}
export function inferMapping(headers:string[]){const out:Record<string,string|null>={};for(const k of Object.keys(aliases)){const h=headers.find(x=>aliases[k].includes(normalizeHeader(x)));out[k]=h??null;}return out;}
export function parseCsv(text:string){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim().length);const parse=(line:string)=>{const a:string[]=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){cur+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){a.push(cur.trim());cur='';}else cur+=c;}a.push(cur.trim());return a;};return lines.map(parse);}
export function validateCsv(text:string,broker:keyof typeof BROKER_PRESETS='mt5'):CsvResult{const matrix=parseCsv(text);const headers=matrix[0]??[];const issues:CsvIssue[]=[];const mapping=inferMapping(headers);for(const key of ['symbol','side','entry','pnl'])if(!mapping[key])issues.push({row:1,field:key,message:`فیلد ضروری ${key} پیدا نشد.`,severity:'error'});const rows=matrix.slice(1).map(c=>Object.fromEntries(headers.map((h,i)=>[h,c[i]??''])));const seen=new Map<string,number>(),duplicates:number[]=[];rows.forEach((r,i)=>{const id=(mapping.id&&r[mapping.id])||`${mapping.date?r[mapping.date]:''}|${mapping.symbol?r[mapping.symbol]:''}|${mapping.entry?r[mapping.entry]:''}`;if(seen.has(id))duplicates.push(i+2);else seen.set(id,i+2);if(mapping.volume&&r[mapping.volume]!==''&&!Number.isFinite(Number(r[mapping.volume])))issues.push({row:i+2,field:'volume',message:'حجم معامله عددی نیست.',severity:'error'});if(mapping.pnl&&r[mapping.pnl]!==''&&!Number.isFinite(Number(r[mapping.pnl])))issues.push({row:i+2,field:'pnl',message:'P/L عددی نیست.',severity:'error'});});for(const d of duplicates)issues.push({row:d,message:'معامله تکراری بر اساس شناسه/کلید ترکیبی تشخیص داده شد.',severity:'warning'});return {headers,rows,issues,duplicates,mapping};}
